// AUTH_USER , SHOW_NOTIFICATION , CLEAR_MSG , IS_LOGOUT
export const AUTH_USER ="AUTH_USER"
export const SHOW_NOTIFICATION="SHOW_NOTIFICATION"
export const CLEAR_MSG="CLEAR_MSG"
export const IS_LOGOUT="IS_LOGOUT"